{% set name = "gradio" %}
{% set version = "5.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz currently not avalaible
  sha256: baab6f549ebe67a44f180e1109ede9597eb17fdaeafab6363d6d7ef17ac07e49
  url: https://github.com/gradio-app/gradio/archive/gradio@{{ version }}.tar.gz


build:
  entry_points:
    - gradio = gradio.cli:cli
    - upload_theme = gradio.themes.upload_theme:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >={{ python_min }}, <3.13
    - aiofiles >=22.0,<24.0
    - anyio >=3.0,<5.0
    #- audioop-lts <1.0 Not yet avalaible yet and only work with python 313
    - fastapi >=0.115.2,<1.0
    - ffmpy
    - gradio-client ==1.5.1
    - httpx >=0.24.1
    - huggingface_hub >=0.25.1
    - jinja2 <4.0
    - markupsafe ~=2.0
    - numpy >=1.0,<3.0
    - orjson ~=3.0
    - packaging
    - pandas >=1.0,<3.0
    - pillow >=8.0,<12.0
    - pydantic >=2.0
    - python-multipart >=0.0.18
    - pydub
    - pyyaml >=5.0,<7.0
    - ruff >=0.2.2
    - safehttpx >=0.1.6,<0.2.0
    - semantic_version ~=2.0
    - starlette >=0.40.0,<1.0
    - tomlkit >=0.12.0,<0.14.0
    - typer >=0.12,<1.0
    - typing-extensions ~=4.0
    - urllib3 ~=2.0
    - uvicorn >=0.14.0

test:
  imports:
    - gradio
  commands:
    - pip check
    - gradio --help
    - upload_theme --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/gradio/
  dev_url: https://github.com/gradio-app/gradio
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Sclare87
    - xhiroga
