{% set name = "gradio" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz
  sha256: 3f81c55164c24bec015dc906da53a3148e18b5c09ad2d86d8568a09dab133eb1

build:
  entry_points:
    - gradio = gradio.cli:cli
    - upload_theme = gradio.themes.upload_theme:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=3.8
    - aiofiles >=22.0,<24.0
    - anyio >=3.0,<5.0
    - fastapi
    - ffmpy
    - gradio-client ==1.4.0
    - httpx >=0.24.1
    - huggingface_hub >=0.25.1
    - jinja2 <4.0
    - markupsafe ~=2.0
    - matplotlib-base >=3.0,<4.dev0
    - numpy >=1.0,<3.0
    - orjson ~=3.0
    - packaging
    - pandas >=1.0,<3.0
    - pillow >=8.0,<11.0
    - pydantic >=2.0
    - pydub
    - python-multipart >=0.0.9
    - pyyaml >=5.0,<7.0
    - ruff >=0.2.2
    - semantic_version ~=2.0
    - tomlkit ==0.12.0
    - typer >=0.12,<1.0
    - typing-extensions ~=4.0
    - urllib3 ~=2.0
    - uvicorn >=0.14.0

test:
  imports:
    - gradio
  commands:
    - pip check
    - gradio --help
    - upload_theme --help
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio/
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Sclare87
    - xhiroga
