{% set name = "gradio" %}
{% set version = "4.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz
  sha256: 9e1ad3e74f71077f91f8717a4c5e404069dfb9f4fa88d9b38f16607152fb7c1a

build:
  entry_points:
    - gradio = gradio.cli:cli
    - upload_theme = gradio.themes.upload_theme:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=3.8
    - aiofiles <24.0,>=22.0
    - altair <6.0,>=4.2.0
    - fastapi
    - ffmpy
    - gradio-client ==0.13.0
    - httpx >=0.24.1
    - huggingface_hub >=0.19.3
    - importlib-resources <7.0,>=1.3
    - jinja2 <4.0
    - markupsafe >=2.0,<3.dev0
    - matplotlib-base >=3.0,<4.dev0
    - numpy >=1.0,<2.dev0
    - orjson >=3.0,<4.dev0
    - packaging
    - pandas <3.0,>=1.0
    - pillow <11.0,>=8.0
    - pydantic >=2.0
    - pydub
    - python-multipart >=0.0.9
    - pyyaml <7.0,>=5.0
    - semantic_version >=2.0,<3.dev0
    - tomlkit ==0.12.0
    - typer <1.0,>=0.9
    - typing-extensions >=4.0,<5.dev0
    - uvicorn >=0.14.0

test:
  imports:
    - gradio
  commands:
    - pip check
    - gradio --help
    - upload_theme --help
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio/
  summary: Python library for easily interacting with trained machine learning models
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - gradio/node/dev/node_modules/esbuild-wasm/LICENSE.md

extra:
  recipe-maintainers:
    - Sclare87
    - xhiroga
